'use strict';

app.bestSellers = kendo.observable({
    onShow: function() {},
    afterShow: function() {},
	data: [
		{
			"Item_Type": "Product",
			"Product_ID": "350",
			"Product_Name": "#GreatestDrips - Deadly Sin",
			"Description": "A sweet, bakery kind of tobaccoish type vape. A description will never do this one justice. Some flavors are made for each other and blend perfectly. Will leave your surroundings smelling like fresh baked cookies and cakes! We have been told that this is very similar to a Crispy treat as well as Cinnamon Buns.&nbsp;Available in 60ml only.",
			"Profile": "bakery, cinnamon, tobacco",
			"Price": "23.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "865",
			"Product_Image_File": "deadlysin_800x800__78820.jpg",
			"Product_Image_Path": "p/506/deadlysin_800x800__78820.jpg",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/p/506/deadlysin_800x800__78820.jpg",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "0",
			"Category_ID": "48",
			"Category_Name": "#GreatestDrips",
			"Category_Path": "E-Liquid/#GreatestDrips",
			"Date_Added": "05/26/2016",
			"Date_Modified": "09/05/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "347",
			"Product_Name": "#GreatestDrips - Zombie Blood",
			"Description": "Mixed from the blood of the innocent. This e-liquid is the nectar of the undead. One of a kind vape not found anywhere else. It's Strawberry Gummy Candy with a kick.&nbsp;Available in 60ml only. This e-liquid is black light responsive!",
			"Profile": "fruit, berries, candy",
			"Price": "23.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "859",
			"Product_Image_File": "zombieblood_800x800__71221.jpg",
			"Product_Image_Path": "n/123/zombieblood_800x800__71221.jpg",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/n/123/zombieblood_800x800__71221.jpg",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "0",
			"Category_ID": "48",
			"Category_Name": "#GreatestDrips",
			"Category_Path": "E-Liquid/#GreatestDrips",
			"Date_Added": "05/26/2016",
			"Date_Modified": "09/06/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "365",
			"Product_Name": "Ice Ice Baby (VG)",
			"Description": "This is a refreshing, cold shot of Wintergreen! As a matter of fact, this vape gives you that fresh feeling of brushing your teeth or popping a mint in your mouth. Sweet, cold and delicious!",
			"Profile": "menthol, cold",
			"Price": "23.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "905",
			"Product_Image_File": "iceicebaby__73580.1479869875.1280.1280.jpg",
			"Product_Image_Path": "server4600/6ht73/products/366/images/905/iceicebaby__73580.1479869875.1280.1280.jpg",
			"Product_Image_URL": "http://cdn2.bigcommerce.com/server4600/6ht73/products/366/images/905/iceicebaby__73580.1479869875.1280.1280.jpg?c=2",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "0",
			"Category_ID": "52",
			"Category_Name": "Cool Collective",
			"Category_Path": "E-Liquid/Cool Collective",
			"Date_Added": "12/14/2016",
			"Date_Modified": "12/14/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "85",
			"Product_Name": "El Kamino",
			"Description": " A tobacco that has background notes of graham, cocoa, hint of sweet. It will remind you of a nutty robust cigar packed with flavor.",
			"Profile": "tobacco",
			"Price": "5.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "744",
			"Product_Image_File": "ElKamino__16630.png",
			"Product_Image_Path": "m/431/ElKamino__16630.png",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/m/431/ElKamino__16630.png",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "0",
			"Category_ID ": "18",
			"Category_Name": "Signature Blends",
			"Category_Path": "E-Liquid/Signature Blends",
			"Date_Added": "03/09/2013",
			"Date_Modified ": "09/07/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "93",
			"Product_Name": "Melon Boba",
			"Description": "The best medley of melons infused with a hint of cream as well as a refreshing hint of mint. A blast of relaxing and sweet flavors balanced to perfection.",
			"Profile": "cold, fruit, cream",
			"Price": "5.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "736",
			"Product_Image_File": "MelonBoba__30577.png",
			"Product_Image_Path": "n/801/MelonBoba__30577.png",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/n/801/MelonBoba__30577.png",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "1",
			"Category_ID": "18",
			"Category_Name": "Signature Blends",
			"Category_Path": "E-Liquid/Signature Blends",
			"Date_Added": "03/09/2013",
			"Date_Modified": "09/07/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "188",
			"Product_Name": "High Five",
			"Description": "A classy blend of a natural oak tobacco, madagascar vanilla and aged bourbon. It will prove to be one of the best tobacco vapes on the market. This is a high VG liquid",
			"Profile": "bakery, cream, tobacco, liquor",
			"Price": "5.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "706",
			"Product_Image_File": "High_Five__05611.png",
			"Product_Image_Path": "n/345/High_Five__05611.png",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/n/345/High_Five__05611.png",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "0",
			"Category_ID": "26",
			"Category_Name": "Nebbia Collection",
			"Category_Path": "E-Liquid/Nebbia Collection",
			"Date_Added": "12/20/2013",
			"Date_Modified": "09/06/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "76",
			"Product_Name": "9 2 5",
			"Description": "Is it coffee? Is it chocolate? Wait, no it's Tiramisu, well now it's changing again, oh wow, now it's espresso, wait... Yeah, even we are amazed at how it changes as you vape. The more you vape, the more flavors come through! If you can, allow this one to steep for a week. Trust us, it's worth the wait.",
			"Profile": "beverage, chocolate, bakery",
			"Price": "5.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "674",
			"Product_Image_File": "925__11261.png",
			"Product_Image_Path": "i/373/925__11261.png",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/i/373/925__11261.png",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "1",
			"Category_ID": "18",
			"Category_Name": "Signature Blends",
			"Category_Path": "E-Liquid/Signature Blends",
			"Date_Added": "03/08/2013",
			"Date_Modified": "09/07/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "349",
			"Product_Name": "#GreatestDrips - Pink Pulldown",
			"Description": "We took a little Raspberry, a little Pomegranate and then added a couple of secret ingredients to give you an amazing vape. If you want to know what it tastes like, it tastes pink!&nbsp;Available in 60ml only.",
			"Profile": "fruit, berries",
			"Price": "23.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "863",
			"Product_Image_File": "pinkpulldown_800x800__36533.jpg",
			"Product_Image_Path": "w/787/pinkpulldown_800x800__36533.jpg",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/w/787/pinkpulldown_800x800__36533.jpg",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "0",
			"Category_ID": "48",
			"Category_Name": "#GreatestDrips",
			"Category_Path": "E-Liquid/#GreatestDrips",
			"Date_Added": "05/26/2016",
			"Date_Modified": "09/06/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "142",
			"Product_Name": "Cozmic Berries",
			"Description": "This e-liquid will remind you of your favorite bowl of cereal from your early days. Berry goodness with hidden notes of the worlds best cereal with a crunch.",
			"Profile": "cereal, cream, fruit",
			"Price": "5.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "681",
			"Product_Image_File": "Cozmic_Berries__31278.png",
			"Product_Image_Path": "i/935/Cozmic_Berries__31278.png",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/i/935/Cozmic_Berries__31278.png",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "2",
			"Category_ID": "20",
			"Category_Name": "The Virtu Line",
			"Category_Path": "E-Liquid/The Virtu Line",
			"Date_Added": "08/26/2013",
			"Date_Modified": "09/06/2016"
		},
		{
			"Item_Type": "Product",
			"Product_ID": "86",
			"Product_Name": "English Bulldog",
			"Description": " Reminisent of a fine pipe, it 's a vape with some attitude. A little sweet, a little nutty with undertones of something fresh, maybe even tropical mixed in along the way. Normally we disclose some of the flavors, but this one you have to try for yourself. Even if you don't like Tobacco vapes,this one will impress.",
			"Profile": "tobacco",
			"Price": "5.99",
			"Product_Not_Visible": "0",
			"Product_Visible": "1",
			"Product_Image_ID": "743",
			"Product_Image_File": "EnglishBulldog__04013.png",
			"Product_Image_Path": "w/733/EnglishBulldog__04013.png",
			"Product_Image_URL": "http://www.goodlifevapor.com/product_images/w/733/EnglishBulldog__04013.png",
			"Product_Image_Is_Thumbnail": "1",
			"Product_Image_Index": "1",
			"Category_ID": "18",
			"Category_Name": "Signature Blends",
			"Category_Path": "E-Liquid/Signature Blends",
			"Date_Added": "03/09/2013",
			"Date_Modified": "09/06/2016"
		}
	]
});
app.localization.registerView('bestSellers');

// START_CUSTOM_CODE_bestSellers
// Add custom code here. For more information about custom code, see http://docs.telerik.com/platform/screenbuilder/troubleshooting/how-to-keep-custom-code-changes

// END_CUSTOM_CODE_bestSellers