'use strict';

var flavorData = [{
	"Item_Type": "Product",
	"Product_ID": "76",
	"Product_Name": "9 2 5",
	"Description": "Is it coffee? Is it chocolate? Wait, no it's Tiramisu, well now it's changing again, oh wow, now it's espresso, wait... Yeah, even we are amazed at how it changes as you vape. The more you vape, the more flavors come through! If you can, allow this one to steep for a week. Trust us, it's worth the wait.",
	"Profile": "beverage, chocolate, bakery",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "674",
	"Product_Image_File": "925__11261.png",
	"Product_Image_Path": "i/373/925__11261.png",
	"Product_Image_URL": "productimages/9_2_5.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/08/2013",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "78",
	"Product_Name": "Black, Blue & Bloody",
	"Description": "A berry vape that provides notes of everything in the berry spectrum. No menthol, nothing but sweet, tangy berries. Sounds simple but the goal was to get multiple berries at different stages of the entire vaping experience. It's a layered vape that will change dynamics as you vape.",
	"Profile": "berries, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "749",
	"Product_Image_File": "Black_Blue_Bloody__44395.png",
	"Product_Image_Path": "t/566/Black_Blue_Bloody__44395.png",
	"Product_Image_URL": "productimages/black_blue_bloody.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/08/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "79",
	"Product_Name": "Blue Swag",
	"Description": "Sweet and tangy blueberry mixed with the finest swag. You won't be able to put this down. Great in a tank but designed for all the drippers out there.",
	"Profile": "berries, fruit, tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "748",
	"Product_Image_File": "BlueSwag__82061.png",
	"Product_Image_Path": "x/957/BlueSwag__82061.png",
	"Product_Image_URL": "productimages/blue_swag.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "80",
	"Product_Name": "Blueberry Morning",
	"Description": "Others have Blueberry Waffles, but not like this. You have to taste this to believe it. Very addictive flavor. You taste all layers of this favorite breakfast delight.",
	"Profile": "bakery, berries, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "747",
	"Product_Image_File": "BlueberryMorning__79889.png",
	"Product_Image_Path": "i/898/BlueberryMorning__79889.png",
	"Product_Image_URL": "productimages/blueberry_morning.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "81",
	"Product_Name": "Butterscotch Yo!",
	"Description": "Now we have vaped all kinds of Butterscotch juice. This, however, is a deep, rich, true butterscotch flavor that only gets better with age. Steeping will do this e-liquid good. We recommend at least a week to get the sweetness and richness of this flavor.",
	"Profile": "candy, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "746",
	"Product_Image_File": "ButterscotchYo__99988.png",
	"Product_Image_Path": "v/738/ButterscotchYo__99988.png",
	"Product_Image_URL": "productimages/butterscotch_yo.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "84",
	"Product_Name": "Deadly Sin",
	"Description": "A sweet, bakery kind of tobaccoish type vape. A description will never do this one justice. Some flavors are made for each other and blend perfectly. The throat hit is there, the flavor is outstanding, the blend is a 50/50. Will leave your surroundings smelling like fresh baked cookies and cakes! I have been told that this is very similar to a Crispy treat as well as Cinnamon Buns.",
	"Profile": "bakery, cinnamon, tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "686",
	"Product_Image_File": "Deadly_Sin__62161.png",
	"Product_Image_Path": "n/308/Deadly_Sin__62161.png",
	"Product_Image_URL": "productimages/deadly_sin.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID ": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified ": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "85",
	"Product_Name": "El Kamino",
	"Description": " A tobacco that has background notes of graham, cocoa, hint of sweet. It will remind you of a nutty robust cigar packed with flavor.",
	"Profile": "tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "744",
	"Product_Image_File": "ElKamino__16630.png",
	"Product_Image_Path": "m/431/ElKamino__16630.png",
	"Product_Image_URL": "productimages/el_kamino.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID ": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified ": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "86",
	"Product_Name": "English Bulldog",
	"Description": " Reminisent of a fine pipe, it 's a vape with some attitude. A little sweet, a little nutty with undertones of something fresh, maybe even tropical mixed in along the way. Normally we disclose some of the flavors, but this one you have to try for yourself. Even if you don't like Tobacco vapes,this one will impress.",
	"Profile": "tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "743",
	"Product_Image_File": "EnglishBulldog__04013.png",
	"Product_Image_Path": "w/733/EnglishBulldog__04013.png",
	"Product_Image_URL": "productimages/english_bulldog.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "87",
	"Product_Name": "Extreme Mint",
	"Description": "Sweet peppermint with a lot of cold! No menthol options for more or less. **NOTE** If you do not like menthol, do not buy this e-liquid",
	"Profile": "menthol, cold",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "742",
	"Product_Image_File": "Extreme_Mint__57539.png",
	"Product_Image_Path": "u/180/Extreme_Mint__57539.png",
	"Product_Image_URL": "productimages/extreme_mint.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "88",
	"Product_Name": "Frozen Ape",
	"Description": "A very frozen grape. Simple and tasty! **NOTE** If you do not like menthol, do not buy this e-liquid.",
	"Profile": "menthol, fruit, cold",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "741",
	"Product_Image_File": "FrozenApe__38927.png",
	"Product_Image_Path": "p/728/FrozenApe__38927.png",
	"Product_Image_URL": "productimages/frozen_ape.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "89",
	"Product_Name": "Frozen GA Peach",
	"Description": "A fresh Georgia peach covered in ice! More than just a cold peach, it is frozen with all the flavor you expect from Georgia's finest fruit! **NOTE** If you do not like menthol, do not buy this e-liquid.",
	"Profile": "menthol, fruit, cold",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "740",
	"Product_Image_File": "FrozenGAPeach__78056.png",
	"Product_Image_Path": "w/224/FrozenGAPeach__78056.png",
	"Product_Image_URL": "productimages/frozen_ga_peach.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "91",
	"Product_Name": "Ice Water",
	"Description": "Watermelon and Peppermint blended to perfection! Let it steep! TRUST ME! The longer it steeps, the juicier the watermelon gets! **NOTE** If you do not like menthol, do not buy this e-liquid.",
	"Profile": "cold, menthol, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "738",
	"Product_Image_File": "IceWater__45417.png",
	"Product_Image_Path": "q/852/IceWater__45417.png",
	"Product_Image_URL": "productimages/ice_water.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/04/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "92",
	"Product_Name": "Magic Fairy",
	"Description": "It's a citrus absinthe with a twist! This e-liquid gets better with age. If you can let it steep, you will not be disappointed. It's good out of the mailbox, but the beauty comes out after a week or so of steep time.",
	"Profile": "citrus, licorice",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "737",
	"Product_Image_File": "MagicFairy__59150.png",
	"Product_Image_Path": "f/946/MagicFairy__59150.png",
	"Product_Image_URL": "productimages/magic_fairy.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "93",
	"Product_Name": "Melon Boba",
	"Description": "The best medley of melons infused with a hint of cream as well as a refreshing hint of mint. A blast of relaxing and sweet flavors balanced to perfection.",
	"Profile": "cold, fruit, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "736",
	"Product_Image_File": "MelonBoba__30577.png",
	"Product_Image_Path": "n/801/MelonBoba__30577.png",
	"Product_Image_URL": "productimages/melon_boba.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "94",
	"Product_Name": "Nana's Nuts",
	"Description": "Banana Nut Bread that is grandma approved! Who knew Nana's nuts would be this tasty?",
	"Profile": "bakery",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "735",
	"Product_Image_File": "NanasNuts__74765.png",
	"Product_Image_Path": "e/003/NanasNuts__74765.png",
	"Product_Image_URL": "productimages/nanas_nuts.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "98",
	"Product_Name": "Pink Cupcakes",
	"Description": "Rich cupcake with a sweet strawberry frosting on top. The cure for any sweet tooth.",
	"Profile": "bakery, berries, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "731",
	"Product_Image_File": "PinkCupcake__99275.png",
	"Product_Image_Path": "d/152/PinkCupcake__99275.png",
	"Product_Image_URL": "productimages/pink_cupcakes.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "99",
	"Product_Name": "Razzled",
	"Description": "Hey, we know that you like blue raspberry candy! Add menthol to get the a cold version of the Blue Raspberry candy!",
	"Profile": "candy, berries, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "637",
	"Product_Image_File": "razzled__38402.jpg",
	"Product_Image_Path": "s/391/razzled__38402.jpg",
	"Product_Image_URL": "productimages/razzled.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID ": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified ": "09/04/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "100",
	"Product_Name": "Red Head",
	"Description": " A tangy Cranberry with a sweet peachy finish.",
	"Profile": "fruit, tropical",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "729",
	"Product_Image_File": "Red_Head__95698.png",
	"Product_Image_Path": "o/493/Red_Head__95698.png",
	"Product_Image_URL": "productimages/red_head.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "103",
	"Product_Name": "Shivering Zebra",
	"Description": "Fruit Stripe Gum mixed with something to give it the perfect flavor. Oh, and don't forget the fact that it's chilled to perfection! It's cold but oh so good! **NOTE** If you do not like menthol, do not buy this e-liquid.This juice is notorious for burning coils. The lifespan of your coils will be less when using this liquid.",
	"Profile": "candy, cold, menthol",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "726",
	"Product_Image_File": "ShiveringZebra_copy__12818.png",
	"Product_Image_Path": "k/017/ShiveringZebra_copy__12818.png",
	"Product_Image_URL": "productimages/shivering_zebra.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "108",
	"Product_Name": "Zombie Blood",
	"Description": "Mixed from the blood of the innocent. This e-liquid is the nectar of the undead. One of a kind vape not found anywhere else. It's Strawberry Gummy Candy with a kick. Add menthol to get the flavor previously known as \"Zombie Brains\"",
	"Profile": "candy, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "724",
	"Product_Image_File": "ZombieBrains__14680.png",
	"Product_Image_Path": "e/905/ZombieBrains__14680.png",
	"Product_Image_URL": "productimages/zombie_blood.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "113",
	"Product_Name": "Eve's Mistake",
	"Description": "A sweet green apple with a whole bunch of menthol. If you don't like menthol, this one is not for you. BUT if you do like menthol, this is the ultimate vape!",
	"Profile": "fruit, tart, licorice, menthol",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "723",
	"Product_Image_File": "EvesMistake__28491.png",
	"Product_Image_Path": "a/725/EvesMistake__28491.png",
	"Product_Image_URL": "productimages/eves_mistake.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "116",
	"Product_Name": "Black Fairy",
	"Description": "The second of the \"Fairies\" comes to life with Absinthe and Blackberry with of course, an added twist. This time, the twist is not menthol. It's a smooth subtle absinthe vape that will leave your taste buds tingling on your tongue.&nbsp;",
	"Profile": "berries, licorice, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "721",
	"Product_Image_File": "BlackFairy__32666.png",
	"Product_Image_Path": "r/905/BlackFairy__32666.png",
	"Product_Image_URL": "productimages/black_fairy.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/28/2013",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "117",
	"Product_Name": "Atom Bomb",
	"Description": "An explosion of Green Apple and Raspberry with a hint of peppermint and a few other secret ingredients. Choose your destiny!",
	"Profile": "cold, fruit, menthol",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "676",
	"Product_Image_File": "Atom_Bomb__57722.png",
	"Product_Image_Path": "e/137/Atom_Bomb__57722.png",
	"Product_Image_URL": "productimages/atom_bomb.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/28/2013",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "118",
	"Product_Name": "Twilight Zone",
	"Description": "You are traveling through another dimension, a dimension not only of sight and sound but of taste. A journey into a wondrous land of Pineapples, Raspberries and wonder. Next stop, the Twilight Zone!",
	"Profile": "berries, tropical, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "720",
	"Product_Image_File": "TwilightZone__51873.png",
	"Product_Image_Path": "t/570/TwilightZone__51873.png",
	"Product_Image_URL": "productimages/twilight_zone.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/28/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "119",
	"Product_Name": "Baja Breeze",
	"Description": "A tropical lime flavored soda from your favorite late night taco stop after a night out on the town.",
	"Profile": "beverage, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "677",
	"Product_Image_File": "Baja_Breeze__60091.png",
	"Product_Image_Path": "v/668/Baja_Breeze__60091.png",
	"Product_Image_URL": "productimages/baja_breeze.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "03/28/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "121",
	"Product_Name": "Shamrock Fairy",
	"Description": "A creamy mint flavored milkshake with shades of Abisinthe. Yes, that's right, Absinthe. Surprisingly, these flavors are the perfect match. If vanilla mint milkshakes with a twist of fairy sounds good to you, give this one a try. We promise it won't disappoint. For a cold version, add some menthol!",
	"Profile": "menthol, cream, licorice",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "719",
	"Product_Image_File": "ShamrockFairy__75444.png",
	"Product_Image_Path": "x/592/ShamrockFairy__75444.png",
	"Product_Image_URL": "productimages/shamrock_fairy.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "05/19/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "131",
	"Product_Name": "Plain Jane",
	"Description": "Good Life is best known for the combination of odd ball flavors, we do however feel that some flavors are best left alone. Plain Jane is a straight forward vanilla. It's smooth, it's very dense, it's rich. It's delicious. There are other Vanilla's and then there is Vanilla \"done right\"",
	"Profile": "cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "716",
	"Product_Image_File": "PlainJane__03169.png",
	"Product_Image_Path": "h/304/PlainJane__03169.png",
	"Product_Image_URL": "productimages/plain_jane.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "07/08/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "142",
	"Product_Name": "Cozmic Berries",
	"Description": "This e-liquid will remind you of your favorite bowl of cereal from your early days. Berry goodness with hidden notes of the worlds best cereal with a crunch.",
	"Profile": "cereal, cream, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "681",
	"Product_Image_File": "Cozmic_Berries__31278.png",
	"Product_Image_Path": "i/935/Cozmic_Berries__31278.png",
	"Product_Image_URL": "productimages/cozmic_berries.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "2",
	"Category_ID": "20",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "08/26/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "143",
	"Product_Name": "Apes Chew",
	"Description": "Welcome to the Good Life family! Chewing gum is a staple in every person's life. This is a banana fruit chewing gum vape that will never lose flavor and never get old.",
	"Profile": "candy, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "675",
	"Product_Image_File": "Apes_Chew__80655.png",
	"Product_Image_Path": "e/852/Apes_Chew__80655.png",
	"Product_Image_URL": "productimages/apes_chew.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "20",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "08/26/2013",
	"Date_Modified": "09/02/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "144",
	"Product_Name": "Pink Pulldown",
	"Description": "We took a little Raspberry, a little Pomegranate and then added a couple of secret ingredients to give you an amazing vape. If you want to know what it tastes like, it tastes pink!",
	"Profile": "berries, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "683",
	"Product_Image_File": "Pink_Pulldown__82931.png",
	"Product_Image_Path": "p/063/Pink_Pulldown__82931.png",
	"Product_Image_URL": "productimages/pink_pulldown.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "20",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "08/26/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "145",
	"Product_Name": "Sweet Criminal",
	"Description": "Welcome to the Good Life family! The perfect poolside drink for the summer. Light melon with perfect pineapple garnished with a mint leaf. Close your eyes and you will swear a mini umbrella is there as well.",
	"Profile": "beverage, fruit, tropical",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "715",
	"Product_Image_File": "Sweet_Criminal__29536.png",
	"Product_Image_Path": "c/669/Sweet_Criminal__29536.png",
	"Product_Image_URL": "productimages/sweet_criminal.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "20",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "08/26/2013",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "146",
	"Product_Name": "Breathless Mahoney",
	"Description": "The absolute best fresh Watermelon vape on the planet. Well... we think so at least",
	"Profile": "fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "714",
	"Product_Image_File": "Breathless_Mahoney__76963.png",
	"Product_Image_Path": "q/093/Breathless_Mahoney__76963.png",
	"Product_Image_URL": "productimages/breathless_mahoney.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "20",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "08/26/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "147",
	"Product_Name": "Strawberry Obsession",
	"Description": "Strawberry done right. This flavor is freshly picked strawberry straight off the vine! Sweet succulent strawberry fields forever!",
	"Profile": "fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "713",
	"Product_Image_File": "StrawberryObsession__00612.png",
	"Product_Image_Path": "d/359/StrawberryObsession__00612.png",
	"Product_Image_URL": "productimages/strawberry_obsession.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "08/26/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "150",
	"Product_Name": "Mexican Hat Dance",
	"Description": "After a long day, you want to relax with a adult beverage. Well this is a Raspberry Margarita blended to absolute perfection. This is a shop favorite!",
	"Profile": "beverage, tropical, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "712",
	"Product_Image_File": "MexicanHatDance__28856.png",
	"Product_Image_Path": "q/062/MexicanHatDance__28856.png",
	"Product_Image_URL": "productimages/mexican_hat_dance.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "09/06/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "156",
	"Product_Name": "Circus! Circus!",
	"Description": "Blue cotton candy. The best fluffy sugar taste straight from your local fair!",
	"Profile": "candy, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "711",
	"Product_Image_File": "Circus_Circus__79266.png",
	"Product_Image_Path": "g/162/Circus_Circus__79266.png",
	"Product_Image_URL": "productimages/circus_circus.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "11/03/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "188",
	"Product_Name": "High Five",
	"Description": "A classy blend of a natural oak tobacco, madagascar vanilla and aged bourbon. It will prove to be one of the best tobacco vapes on the market. This is a high VG liquid",
	"Profile": "bakery, cream, tobacco, liquor",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "706",
	"Product_Image_File": "High_Five__05611.png",
	"Product_Image_Path": "n/345/High_Five__05611.png",
	"Product_Image_URL": "productimages/high_five.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "26",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "12/20/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "190",
	"Product_Name": "Orange Blossom",
	"Description": "A fresh baked muffin on the inhale with a fresh, naturally sweetened blood orange on the exhale. This is a high VG e-liquid",
	"Profile": "fruit, citrus, bakery",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "704",
	"Product_Image_File": "Orange_Blossom__11647.png",
	"Product_Image_Path": "n/831/Orange_Blossom__11647.png",
	"Product_Image_URL": "productimages/orange_blossom.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/20/2013",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "191",
	"Product_Name": "Kustard",
	"Description": "Many have vanilla custard flavored e-liquid. So what sets this apart? We took the idea of custard and added all aspects you would find in homemade custard. It's sweet, it's creamy, it's dense, it's a little eggy (in a good way). We know custard lovers will find this to be the new answer for that perfect vanilla custard. This is a high VG e-liquid.",
	"Profile": "bakery, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "703",
	"Product_Image_File": "Kustard__89242.png",
	"Product_Image_Path": "r/674/Kustard__89242.png",
	"Product_Image_URL": "productimages/kustard.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/20/2013",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "194",
	"Product_Name": "Southern Shine",
	"Description": "Apple pie with a slight kick of liquor. A big hit with anyone that tries it. We feel as if we are pushing the limits with a flavor like this. Complex and very, very tasty. This is a high VG e-liquid.",
	"Profile": "liquor, fruit, tart",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "702",
	"Product_Image_File": "SouthernShine__45251.png",
	"Product_Image_Path": "a/147/SouthernShine__45251.png",
	"Product_Image_URL": "productimages/southern_shine.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "02/03/2014",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "202",
	"Product_Name": "Decadence",
	"Description": "A smooth velvety blend that promises to deliver. Creamy sweet butterscotch cream that will not disappoint even the pickiest of pallets.&nbsp;",
	"Profile": "cream, candy",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "700",
	"Product_Image_File": "Decedance__17046.png",
	"Product_Image_Path": "c/790/Decedance__17046.png",
	"Product_Image_URL": "productimages/decadence.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "04/13/2014",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "203",
	"Product_Name": "Red Berry Dream",
	"Description": "Strawberries and cream never tasted so good. It's a trip back to your earlier years with sweet strawberry and delicious cream. Some have said that it gives you the impression of a glass sweet Strawberry milk.&nbsp;",
	"Profile": "fruit, candy, cream, berries",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "699",
	"Product_Image_File": "Red_Berry_Dream__93532.png",
	"Product_Image_Path": "n/404/Red_Berry_Dream__93532.png",
	"Product_Image_URL": "productimages/red_berry_dream.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "04/13/2014",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "204",
	"Product_Name": "Purple Stuff",
	"Description": "Sugar, Water, Purple. Purple Drank! Plain and simple but oh so good for grape lovers!",
	"Profile": "beverage, candy, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "698",
	"Product_Image_File": "Purnurple__31862.png",
	"Product_Image_Path": "l/699/Purnurple__31862.png",
	"Product_Image_URL": "productimages/purple_stuff.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Signature Blends",
	"Category_Path": "E-Liquid/Signature Blends",
	"Date_Added": "04/13/2014",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "222",
	"Product_Name": "Fairy Blood",
	"Description": "This is a little different than the other Fairy liquids. Unlike the other fairies, this one is not screaming with Absinthe. Instead we blended Anise with the perfect Strawberry and the most succulent Clementine orange. The end result is a mouth watering explosion of the most unique fruit you'll ever find. It's absolutely delicious, even for those non-Anise vapers.",
	"Profile": "fruit, candy, licorice",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "696",
	"Product_Image_File": "FairyBlood__33372.png",
	"Product_Image_Path": "u/022/FairyBlood__33372.png",
	"Product_Image_URL": "productimages/fairy_blood.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "09/02/2014",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "364",
	"Product_Name": "Gringo",
	"Description": "Grapes muddled with Mint and blended with sweet Mangos!",
	"Profile": "fruit, candy, menthol, cold",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "900",
	"Product_Image_File": "gringo__55044.1479849506.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/364/images/900/gringo__55044.1479849506.1280.1280.jpg",
	"Product_Image_URL": "productimages/gringo.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "09/02/2014",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "363",
	"Product_Name": "Seriously Nutty",
	"Description": "The absolute best honey nut cereal loaded with fresh, creamy milk!",
	"Profile": "cereal, cream, bakery",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "898",
	"Product_Image_File": "seriouslynutty__85689.1479849380.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/363/images/898/seriouslynutty__85689.1479849380.1280.1280.jpg",
	"Product_Image_URL": "productimages/seriously_nutty.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "09/02/2014",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "256",
	"Product_Name": "Cake Boss",
	"Description": "Give in to gluttony with this decadent German Chocolate Cake smothered in delicious toasted coconut and glazed almonds. This is a high VG e-liquid.",
	"Profile": "chocolate, bakery",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "695",
	"Product_Image_File": "Cake_Boss__63119.png",
	"Product_Image_Path": "v/224/Cake_Boss__63119.png",
	"Product_Image_URL": "productimages/cake_boss.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "36",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "10/07/2014",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "257",
	"Product_Name": "Mini Skirt",
	"Description": "Delicious Honey Dew Melon infused with a light Honeysuckle all brought together by a light, barely there creamy vanilla. This vape will have your taste buds begging for more! This is a high VG e-liquid.",
	"Profile": "fruit, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "694",
	"Product_Image_File": "Mini_Skirt__12072.png",
	"Product_Image_Path": "l/563/Mini_Skirt__12072.png",
	"Product_Image_URL": "productimages/mini_skirt.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "36",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "10/07/2014",
	"Date_Modified": "09/03/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "261",
	"Product_Name": "Schmucker",
	"Description": "Smooth and creamy pineapple accented with fresh strawberry and citrus notes",
	"Profile": "fruit, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "690",
	"Product_Image_File": "Schmucker__64882.png",
	"Product_Image_Path": "t/450/Schmucker__64882.png",
	"Product_Image_URL": "productimages/schmucker.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "36",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "10/07/2014",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "272",
	"Product_Name": "My Boy Blue",
	"Description": "Blueberries and Custard is a staple in the South. Crisp, Sweet Blueberries mixed to perfection with lush, creamy custard. An amazing vape at any temperature!",
	"Profile": "berries, cream, fruit",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "689",
	"Product_Image_File": "My_Boy_Blue__57629.png",
	"Product_Image_Path": "v/108/My_Boy_Blue__57629.png",
	"Product_Image_URL": "productimages/my_boy_blue.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "11/25/2014",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "274",
	"Product_Name": "Deadly Sin (VG)",
	"Description": "A sweet, bakery kind of tobaccoish type vape. A description will never do this one justice. Some flavors are made for each other and blend perfectly. The throat hit is there, the flavor is outstanding, this is the high VG version of the original Deadly Sin. Will leave your surroundings smelling like fresh baked cookies and cakes! I have been told that this is very similar to a Crispy treat as well as Cinnamon Buns.",
	"Profile": "bakery, cinnamon, tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "685",
	"Product_Image_File": "Deadly_Sin__77671.png",
	"Product_Image_Path": "c/094/Deadly_Sin__77671.png",
	"Product_Image_URL": "productimages/deadly_sin_vg.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID ": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "11/25/2014",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "295",
	"Product_Name": "Pop's Pipe",
	"Description": "A sweet French Pipe blended with a lightly spiced Chai Latte and Vanilla Bean. A very sophisticated tobacco vape that is simply irresistible. A perfect morning vape that might just satisfy you throughout the entire day.",
	"Profile": "tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "671",
	"Product_Image_File": "Pops_Pipe__35729.png",
	"Product_Image_Path": "t/479/Pops_Pipe__35729.png",
	"Product_Image_URL": "productimages/pops_pipe.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "02/27/2015",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "296",
	"Product_Name": "Pink Pulldown (VG)",
	"Description": "We took a little Raspberry, a little Pomegranate and then added a couple of secret ingredients to give you an amazing vape. If you want to know what it tastes like, it tastes pink!",
	"Profile": "fruit, berries",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "682",
	"Product_Image_File": "Pink_Pulldown__66615.png",
	"Product_Image_Path": "c/682/Pink_Pulldown__66615.png",
	"Product_Image_URL": "productimages/pink_pulldown_vg.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "03/30/2015",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "299",
	"Product_Name": "Triple Threat",
	"Description": "Traditional Rainbow Sherbet. Sweet raspberries mixed with a tangy lime and a succulent orange. The only thing missing is the bowl and spoon. This is the perfect poolside treat!",
	"Profile": "berries, fruit, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "680",
	"Product_Image_File": "Triple_Threat__80026.png",
	"Product_Image_Path": "a/823/Triple_Threat__80026.png",
	"Product_Image_URL": "productimages/triple_threat.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "36",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "06/09/2015",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "302",
	"Product_Name": "Sacred Bodhi",
	"Description": "Sweet citrus mixed with a fig that tastes as though it were picked straight from the branch of the Bodhi tree and then rounded out with a light sweet Jasmine flower. The liquid is super complex but very easy on the palette. Bright and very refreshing.",
	"Profile": "citrus, fruit, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "752",
	"Product_Image_File": "unnamed__09210.jpg",
	"Product_Image_Path": "w/938/unnamed__09210.jpg",
	"Product_Image_URL": "productimages/sacred_bodhi.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "07/13/2015",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "303",
	"Product_Name": "Zombie Blood (VG)",
	"Description": "Mixed from the blood of the innocent. This e-liquid is the nectar of the undead. One of a kind vape not found anywhere else. It's Strawberry Gummy Candy with a kick. Add menthol to get the flavor previously known as \"Zombie Brains\"",
	"Profile": "fruit, berries, candy",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "755",
	"Product_Image_File": "ZombieBrains_14680__28156.png",
	"Product_Image_Path": "h/894/ZombieBrains_14680__28156.png",
	"Product_Image_URL": "productimages/zombie_blood_vg.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "08/14/2015",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "304",
	"Product_Name": "Ohhh Myyy!!",
	"Description": "The delicious taste of Vanilla Bean Ice Cream blended with sweet Honey and Graham Cracker.",
	"Profile": "cream, bakery",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "757",
	"Product_Image_File": "ohhhmyyy__80125.jpg",
	"Product_Image_Path": "i/227/ohhhmyyy__80125.jpg",
	"Product_Image_URL": "productimages/ohhh_myyy.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "08/24/2015",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "305",
	"Product_Name": "Wallabedamn'd",
	"Description": "Fresh picked Mandarin oranges mixed with the sweetest Georgia peaches and succulent apricots with a smooth creamy finish. It's one of the best citrus based e-liquids on the market.",
	"Profile": "beverage, fruit, citrus, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "758",
	"Product_Image_File": "wallabedamnd__64175.jpg",
	"Product_Image_Path": "p/945/wallabedamnd__64175.jpg",
	"Product_Image_URL": "productimages/wallabedamnd.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "10/02/2015",
	"Date_Modified ": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "306",
	"Product_Name": "2 Scoops",
	"Description": "Delicious, creamy, Mint Chocolate Chip Ice Cream. So amazing it will have you begging for the real thing! This is a non menthol liquid but does have peppermint notes.",
	"Profile": "chocolate, menthol, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "759",
	"Product_Image_File": "2scoops__34597.jpg",
	"Product_Image_Path": "f/384/2scoops__34597.jpg",
	"Product_Image_URL": "productimages/2_scoops.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "10/20/2015",
	"Date_Modified ": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "315",
	"Product_Name": "Pie Gobbler",
	"Description": "A Pumpkin Pie liquid filled with nutmeg,clove,cinnamon and ginger spices.Smooth and creamy with the perfect balance of sweet and spice",
	"Profile": "cinnamon, bakery",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "796",
	"Product_Image_File": "piegobbler__21134.jpg",
	"Product_Image_Path": "b/841/piegobbler__21134.jpg",
	"Product_Image_URL": "productimages/pie_gobbler.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "44",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "11/03/2015",
	"Date_Modified": "08/31/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "317",
	"Product_Name": "GL Reserve",
	"Description": "We all deserve a nightcap. Holidays are when you pull out that perfectly aged single malt scotch to share with your favorite people. This vape is an amazing scotch with a hint of vanilla and even light citrus notes.",
	"Profile": "liquor",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "793",
	"Product_Image_File": "glreserve__69615.jpg",
	"Product_Image_Path": "z/780/glreserve__69615.jpg",
	"Product_Image_URL": "productimages/gl_reserve.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "44",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "11/03/2015",
	"Date_Modified": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "318",
	"Product_Name": "Cranberry Kustard",
	"Description": "Sweet and tangy cranberries paired with a lush vanilla custard. An amazing holiday treat for everyone.",
	"Profile": "fruit, cream, berries",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "795",
	"Product_Image_File": "cranberry_kustard__24097.jpg",
	"Product_Image_Path": "g/150/cranberry_kustard__24097.jpg",
	"Product_Image_URL": "productimages/kustard.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "44",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "11/03/2015",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "323",
	"Product_Name": "Mr.Churro",
	"Description": "The classic Southwest treat!Cinnamon Sugar with Sweet Bread.The perfect dessert vape!",
	"Profile": "cinnamon, bakery, cereal",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "812",
	"Product_Image_File": "mrchurro__73020.jpg",
	"Product_Image_Path": "u/201/mrchurro__73020.jpg",
	"Product_Image_URL": "productimages/mr_churro.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "01/22/2016",
	"Date_Modified ": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "324",
	"Product_Name": "PB Sin",
	"Description": "This is the third evolution of Deadly Sin.Creamy Peanut Butter meets luscious Butterscotch with that same Crispy Treat,Cinnamon Roll,Deadly Sin kick!",
	"Profile": "bakery, cream, cinnamon, tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "836",
	"Product_Image_File": "pb_sin_800x800__90676.jpg",
	"Product_Image_Path": "o/265/pb_sin_800x800__90676.jpg",
	"Product_Image_URL": "productimages/pb_sin.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "26",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "01/22/2016",
	"Date_Modified ": "09/07/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "325",
	"Product_Name": "Toucan Tango",
	"Description": "Fruit Circle cereal with Vanilla Bean Ice Cream instead of Milk.The perfect balance of Fruit and Cream!",
	"Profile": "cereal, fruit, cream",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "837",
	"Product_Image_File": "toucantango__61023.jpg",
	"Product_Image_Path": "v/634/toucantango__61023.jpg",
	"Product_Image_URL": "productimages/toucan_tango.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "36",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "01/22/2016",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "335",
	"Product_Name": "Dew Scoops",
	"Description": "Sweet Honeydew Melon combined with refreshing Pineapple and blended with the perfect Vanilla Bean Ice Cream.",
	"Profile": "fruit, cream",
	"Price": "9.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "839",
	"Product_Image_File": "ss_dew_scoops__82953.jpg",
	"Product_Image_Path": "h/339/ss_dew_scoops__82953.jpg",
	"Product_Image_URL": "productimages/dew_scoops.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "45",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "02/01/2016",
	"Date_Modified": "09/04/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "336",
	"Product_Name": "Foster The Banana",
	"Description": "Delicious ripe Banana topped with creamy Caramel and blended with perfectly aged Rum.",
	"Profile": "fruit, liquor, cream",
	"Price": "9.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "841",
	"Product_Image_File": "ss_foster_the_banana__98434.jpg",
	"Product_Image_Path": "f/725/ss_foster_the_banana__98434.jpg",
	"Product_Image_URL": "productimages/foster_the_banana.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "45",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "02/01/2016",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "337",
	"Product_Name": "Lemony Kickit",
	"Description": "Fresh Lemon combined with a tasty Sugar Cookie and topped with delicious Brown Sugar.",
	"Profile": "fruit, citrus, bakery, cream",
	"Price": "9.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "843",
	"Product_Image_File": "ss_lemony_kickit__44721.jpg",
	"Product_Image_Path": "c/305/ss_lemony_kickit__44721.jpg",
	"Product_Image_URL": "productimages/lemony_kickit.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "45",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "02/01/2016",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "338",
	"Product_Name": "The Revolution",
	"Description": "Fresh picked Raspberry blended with rich Cream Cheese over a tasty Powered Doughnut.",
	"Profile": "berries, cream, fruit",
	"Price": "9.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "846",
	"Product_Image_File": "ss_the_revolution__14358.jpg",
	"Product_Image_Path": "s/407/ss_the_revolution__14358.jpg",
	"Product_Image_URL": "productimages/the_revolution.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "45",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "02/01/2016",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "341",
	"Product_Name": "Gimme S'more",
	"Description": "Smooth Milk Chocolate and melted Marshmallows on a toasted Graham Cracker.",
	"Profile": "chocolate, cream, bakery",
	"Price": "18.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "849",
	"Product_Image_File": "divinity_gimme_smore__13540.jpg",
	"Product_Image_Path": "p/907/divinity_gimme_smore__13540.jpg",
	"Product_Image_URL": "productimages/gimme_smore.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "46",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "04/01/2016",
	"Date_Modified ": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "342",
	"Product_Name": "Tres Cremas",
	"Description": "Sweet Strawberries,Vanilla Bean and Milk Chocolate Ice Cream blended perfectly together. < /p>",
	"Profile": "berries, fruit, cream, chocolate",
	"Price": "18.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "851",
	"Product_Image_File": "divinity_tres_cremas__98191.jpg",
	"Product_Image_Path": "n/244/divinity_tres_cremas__98191.jpg",
	"Product_Image_URL": "productimages/tres_cremas.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "46",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "04/01/2016",
	"Date_Modified ": "09/02/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "344",
	"Product_Name": "Zebra Treats",
	"Description": "America's favorite treat! Yellow Cake with Fresh Cream center covered in White Chocolate Fudge.",
	"Profile": "bakery, chocolate",
	"Price": "18.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "853",
	"Product_Image_File": "divinity_zebra_treats__42434.jpg",
	"Product_Image_Path": "d/842/divinity_zebra_treats__42434.jpg",
	"Product_Image_URL": "productimages/zebra_treats.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "46",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "04/01/2016",
	"Date_Modified": "08/14/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "355",
	"Product_Name": "Hyp Kng",
	"Description": "The world's best Key Lime Cookie! Available in 60ml only!",
	"Profile": "citrus, bakery, cream, cream",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "874",
	"Product_Image_File": "hypkng_keylime_800x800__85928.jpg",
	"Product_Image_Path": "l/821/hypkng_keylime_800x800__85928.jpg",
	"Product_Image_URL": "productimages/hyp_kng.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "49",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "06/17/2016",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "356",
	"Product_Name": "Crusher",
	"Description": "Orange creamy goodness straight from the grove! Available in 60ml only!",
	"Profile": "citrus, cream",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "876",
	"Product_Image_File": "crusher_product_image__80392.jpg",
	"Product_Image_Path": "n/210/crusher_product_image__80392.jpg",
	"Product_Image_URL": "productimages/crusher.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "50",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "07/29/2016",
	"Date_Modified": "09/06/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "357",
	"Product_Name": "Blue Alice",
	"Description": "A light Blueberry Kiwi Creamy Custard that will inspire your muchness! In the final chapter of our tale, Blue Alice represents individuality, curiosity, strength and passion. Her greatest attribute is her ability to journey into the unknown. Alice makes her own path and she will not be told who or how to be. Her imagination and instincts guide her throughout the entire story. She does not fear what lies ahead and when she is faced with the impossible, she doesn't run away. She stands her ground and she fights for what she knows is right. She defends her friends and always remains loyal because she knows that she cannot do it alone. As a community, we have lost our way and torn each other apart time and time again. We have lost sight of the very idea that this revolutionary industry was founded on. We have become a fad and a lifestyle rather than a way to enhance the lives of ourselves and others. We could learn some valuable lessons from Alice, if only we could stop and remember the bigger picture. The flavor of this liquid is much like Alice, a blueberry to represent her kind, sweet nature with a touch of tang from a citrus kiwi fruit that is similar to her witty and strong attitude. It then finishes with a creamy custard to represent her quirky and curious ideals. We all need to wake up and realize that this is not a dream, this is the real world.",
	"Profile": "berries, fruit, cream",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "878",
	"Product_Image_File": "bluealice_product__11345.jpg",
	"Product_Image_Path": "r/135/bluealice_product__11345.jpg",
	"Product_Image_URL": "productimages/blue_alice.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "51",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "08/04/2016",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "358",
	"Product_Name": "Red Queen",
	"Description": "A sour berry&nbsp;and sweet tangerine blended with the perfect snicker doodle sugar cookie that tricks your taste buds. In every story there is a villain. The Red Queen represents the evil, uninformed, antagonist entity that is very similar to the forces trying to end every aspect of the vapor industry. The Red Queen doesn't seek answers to her questions, she screams \"off with their head\" without a moment of thought. All of her choices are made with selfishness, greed, malice and personal gain. The well being of the others in Wonderland plays no part in her thought process. She wants to reign supreme at any and all cost. She is a joke amongst her peers. They become what she wants only to keep their head. However, she does have many weaknesses and flaws that can be exploited. The people of Wonderland must rise up and unify to defeat the queen. The games must stop for the betterment of society. The Red Queen is bitter, a little sour, seemingly sweet to her supporters, and yet everyone snickers and laughs at her ridiculousness behind her back. We took a bitter, semi-sour berry and mixed it with a sweet tangerine, and then we added in a snicker doodle sugar cookie to make a truly amazing vape. Much like the queen, the flavor changes as you vape and it tricks your taste buds. Conform to The Red Queen or it's off with your head!",
	"Profile": "citrus, bakery, berries, fruit, cinnamon",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "882",
	"Product_Image_File": "redqueen_product__23333.jpg",
	"Product_Image_Path": "m/679/redqueen_product__23333.jpg",
	"Product_Image_URL": "productimages/red_queen.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "51",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "08/04/2016",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "359",
	"Product_Name": "The Hatter",
	"Description": "A completely original white tea with a splash of earl grey, youth berries and subtle notes of citrus. The Hatter is bold, original, unique and a little quirky, just like the beginning of the vapor industry. A select few people with some big dreams were trying to find their place in the world. Armed with very little resources and a lot of ingenuity, these people pursue a crazy dream that could potentially change history and help society rid itself of a big problem. In the beginning, we were looked at as mad scientists and we seemed to be chasing an impossible dream. However, we know that it takes a crazy idea to impact lives and change the world. There is nothing like The Hatter. He cannot be duplicated. The Hatter stands on the playful side of truth. There is no rhyme or reason with him, yet somehow he makes perfect sense, much like a variety of different flavors thrown into a bottle. Some are sweet, some are savory, some are fruity and even a little sour. The flavors come together to form a perfect balance. They playfully trick your mind into being at the tea party. With all the desserts being passed around, you will certainly need something to wash it all down. The Hatter delivers a perfect white tea, mixed with a splash of earl grey, youth berries, and hints of sweet citrus. This is a drink so divine that it can't be found in the real world. As you drink, you see a magical Cheshire Cat fly by, look at you and say, \"We're all mad in here!\"",
	"Profile": "fruit, berries, tea",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "886",
	"Product_Image_File": "thehatter_product__19847.jpg",
	"Product_Image_Path": "d/886/thehatter_product__19847.jpg",
	"Product_Image_URL": "productimages/the_hatter.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "51",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "08/04/2016",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "360",
	"Product_Name": "White Rabbit",
	"Description": "A delicious butterscotch haystack with candy coated almonds that results in one of the best, most complex flavors. There are moments when you have to settle down and get serious. The White Rabbit represents time. In an industry filled with uncertainty, we have the choice to grow and be great or to fade away and become irrelevant. The life we have chosen is not a game, we do not live our lives just to become mediocre. We have one chance to be who we want to be. Our time should not be limited. Thought and creativity is what sets the strong apart from the weak. The safe bet is not always the most rewarding path to take. There is a thunder coming and to combat this storm, we need a strong foundation. We need time because soon we will be forced to stand up and defend the things we hold so dear. The White Rabbit appears to be soft and sweet, but actually, deep down, it has attitude and it is extremely bold. It is also a guide and he fuels curiosity. The flavor profile fits The White Rabbit so perfectly. Much like the rabbit, butterscotch is a very illusive flavor. We took the idea of a butterscotch haystack and added candy coated almonds to create one of the best, most complex flavors. Follow the white rabbit to buy yourself time to be wonderful.",
	"Profile": "cream, bakery",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "890",
	"Product_Image_File": "whiterabbit_product__83452.jpg",
	"Product_Image_Path": "d/054/whiterabbit_product__83452.jpg",
	"Product_Image_URL": "productimages/white_rabbit.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "51",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "08/04/2016",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "365",
	"Product_Name": "Ice Ice Baby (VG)",
	"Description": "This is a refreshing, cold shot of Wintergreen! As a matter of fact, this vape gives you that fresh feeling of brushing your teeth or popping a mint in your mouth. Sweet, cold and delicious!",
	"Profile": "menthol, cold",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "905",
	"Product_Image_File": "iceicebaby__73580.1479869875.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/366/images/905/iceicebaby__73580.1479869875.1280.1280.jpg",
	"Product_Image_URL": "productimages/ice_ice_baby_vg.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "52",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/14/2016",
	"Date_Modified": "12/14/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "367",
	"Product_Name": "Red Hot Mess",
	"Description": "The fire and ice combination of this liquid makes for an explosion of flavor! Red Hot Cinnamon meets Peppermint menthol.",
	"Profile": "menthol, cold, cinnamon",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "907",
	"Product_Image_File": "iceicebaby__73580.1479869875.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/367/images/907/redhotmess__61967.1479869971.1280.1280.jpg",
	"Product_Image_URL": "productimages/red_hot_mess.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "52",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/14/2016",
	"Date_Modified": "12/14/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "369",
	"Product_Name": "Melo Tea",
	"Description": "Sweet melons meets refreshing bubble tea!",
	"Profile": "fruit, tea, cream, beverage",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "911",
	"Product_Image_File": "melotea__02125.1479870400.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/369/images/911/melotea__02125.1479870400.1280.1280.jpg",
	"Product_Image_URL": "productimages/melo_tea.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "53",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/14/2016",
	"Date_Modified": "12/14/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "370",
	"Product_Name": "Passion Tea",
	"Description": "Passion fruit, Guava and Papaya meets refreshing bubble tea!",
	"Profile": "fruit, tea, cream, beverage",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "913",
	"Product_Image_File": "passiontea__00249.1479870460.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/370/images/913/passiontea__00249.1479870460.1280.1280.jpg",
	"Product_Image_URL": "productimages/passion_tea.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "53",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/14/2016",
	"Date_Modified": "12/14/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "371",
	"Product_Name": "Pearl Tea",
	"Description": "Pear and Lychee meets refreshing bubble tea!",
	"Profile": "fruit, tea, cream, beverage",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "915",
	"Product_Image_File": "pearltea__51420.1479870554.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/371/images/915/pearltea__51420.1479870554.1280.1280.jpg",
	"Product_Image_URL": "productimages/pearl_tea.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "53",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/14/2016",
	"Date_Modified": "12/14/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "372",
	"Product_Name": "Sorrel Tea",
	"Description": "Hibiscus and Boysenberry meets refreshing bubble tea!",
	"Profile": "fruit, tea, cream, beverage",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "917",
	"Product_Image_File": "sorreltea__82114.1479870609.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/372/images/917/sorreltea__82114.1479870609.1280.1280.jpg",
	"Product_Image_URL": "productimages/sorrel_tea.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "53",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/14/2016",
	"Date_Modified": "12/14/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "373",
	"Product_Name": "Thai Tea",
	"Description": "Spiced Thai flavors meet refreshingly good bubble tea!",
	"Profile": "fruit, tea, cream, beverage",
	"Price": "23.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "919",
	"Product_Image_File": "thaitea__58740.1479870667.1280.1280.jpg",
	"Product_Image_Path": "server4600/6ht73/products/373/images/919/thaitea__58740.1479870667.1280.1280.jpg",
	"Product_Image_URL": "productimages/pearl_tea.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "0",
	"Category_ID": "53",
	"Category_Name": "High VG Blends",
	"Category_Path": "E-Liquid/High VG Blends",
	"Date_Added": "12/14/2016",
	"Date_Modified": "12/14/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "97394759",
	"Product_Name": "Camilla Blend",
	"Description": "The absolute best RY4 Tobacco on the market! Creamy vanilla and caramel meets a sweet, rich tobacco!",
	"Profile": "tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "748",
	"Product_Image_File": "BlueSwag__82061.png",
	"Product_Image_Path": "x/957/BlueSwag__82061.png",
	"Product_Image_URL": "productimages/camilla_blend.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "78347583",
	"Product_Name": "Marble Light",
	"Description": "The gold standard when it comes to cigarettes. The taste of a light cigarette without the bad stuff!",
	"Profile": "tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "748",
	"Product_Image_File": "BlueSwag__82061.png",
	"Product_Image_Path": "x/957/BlueSwag__82061.png",
	"Product_Image_URL": "productimages/marble_light.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "62352292",
	"Product_Name": "Marble Red",
	"Description": "The favorite cigarette choice of cowboys everywhere! Bold and flavorful tobacco with a big throat hit!",
	"Profile": "berries, fruit, tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "748",
	"Product_Image_File": "BlueSwag__82061.png",
	"Product_Image_Path": "x/957/BlueSwag__82061.png",
	"Product_Image_URL": "productimages/marble_red.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "2346823648",
	"Product_Name": "Marble Menthol",
	"Description": "The smoothest Menthol cigarette flavor on the market! If you want the flavor of a menthol cigarette, look no further!",
	"Profile": "menthol, tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "748",
	"Product_Image_File": "BlueSwag__82061.png",
	"Product_Image_Path": "x/957/BlueSwag__82061.png",
	"Product_Image_URL": "productimages/marble_menthol.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "8348563",
	"Product_Name": "Morning After",
	"Description": "Coffee and cigarettes all in one liquid! Black coffee meets smooth tobacco.",
	"Profile": "beverage, tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "748",
	"Product_Image_File": "BlueSwag__82061.png",
	"Product_Image_Path": "x/957/BlueSwag__82061.png",
	"Product_Image_URL": "productimages/morning_after.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}, {
	"Item_Type": "Product",
	"Product_ID": "8263846824",
	"Product_Name": "Turkish Smoke",
	"Description": "A delicious version of the famous desert ship blend. Turkish Smoke offers a tangy bold tobacco flavor.",
	"Profile": "tobacco",
	"Price": "5.99",
	"Product_Not_Visible": "0",
	"Product_Visible": "1",
	"Product_Image_ID": "748",
	"Product_Image_File": "BlueSwag__82061.png",
	"Product_Image_Path": "x/957/BlueSwag__82061.png",
	"Product_Image_URL": "productimages/turkish_smoke.png",
	"Product_Image_Is_Thumbnail": "1",
	"Product_Image_Index": "1",
	"Category_ID": "18",
	"Category_Name": "Tobacco Blends",
	"Category_Path": "E-Liquid/Tobacco Blends",
	"Date_Added": "03/09/2013",
	"Date_Modified": "09/05/2016"
}];

flavorData.sort(function(a, b){
	var nameA=a.Product_Name.toLowerCase(), nameB=b.Product_Name.toLowerCase()
	if (nameA < nameB) //sort string ascending
		return -1 
	if (nameA > nameB)
		return 1
	return 0 //default return value (no sorting)
});

function getParameterByName(name, url) {
    if (!url) {
      url = window.location.href;
    }
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
        results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, " "));
}

app.flavors = kendo.observable({
    onShow: function() {
		app.flavors.data.sort(function(a, b){
			var nameA=a.Product_Name.toLowerCase(), nameB=b.Product_Name.toLowerCase()
			if (nameA < nameB) //sort string ascending
				return -1 
			if (nameA > nameB)
				return 1
			return 0 //default return value (no sorting)
		});
		var filtertype = app.filtertype;
		var filtername = app.filtername;
		var filter = '.flavor[data-' + filtertype + '*="'+ filtername +'"]';
		$(document).find('.flavor').parent().hide();
		$(document).find(filter).parent().show();
		if (filtername) {
			var profileName = filtername.substr(0,1).toUpperCase()+filtername.substr(1);
			$(document).find('#flavorsScreen .km-view-title span').text('Flavors - '+ profileName);
		}
	},
    afterShow: function() {},
	data: flavorData
});
app.localization.registerView('flavors');

// START_CUSTOM_CODE_flavors
// Add custom code here. For more information about custom code, see http://docs.telerik.com/platform/screenbuilder/troubleshooting/how-to-keep-custom-code-changes

// END_CUSTOM_CODE_flavors